name: Publish roundandround.nl

on:
  push:
    branches:
      - gatsby-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: xmflsct/action-publish-gatsby@v0.6
        with:
          publishBranch: "master"
          token: ${{ secrets.PAT }}
          name: "Zhiyuan Zheng"
          email: "me@xmflsct.com"
